# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

#ÓÇ∂ ÓÇ¥ ÓÇ∞ÓÇ≤
format = """
[ÓÇ∂](color_orange)\
$os\
[ÓÇ∞](bg:color_yellow fg:color_orange)\
$directory\
[ÓÇ∞](fg:color_yellow)\
$fill\
[ÓÇ≤](fg:color_aqua)\
$git_branch\
$git_status\
$git_state\
$git_metrics\
[ÓÇ≤](fg:color_turq bg:color_aqua)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[ÓÇ≤](fg:color_blue bg:color_turq)\
$package\
$docker_context\
$conda\
$pixi\
[ÓÇ≤](fg:color_violet bg:color_blue)\
$username\
$sudo\
[ÓÇ≤](fg:color_bg3 bg:color_violet)\
$cmd_duration\
$battery\
$memory_usage\
[ÓÇ≤](fg:color_bg1 bg:color_bg3)\
$time\
[ÓÇ¥ ](fg:color_bg1)$line_break\
$character
"""

palette = 'gruvbox_dark'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_violet = '#9367ec'
color_blue = '#6788ec'
color_turq = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#4d4d4d'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#a6781b'

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "Û∞ç≤"
Ubuntu = "Û∞ïà"
SUSE = "Ôåî"
Raspbian = "Û∞êø"
Mint = "Û∞£≠"
Macos = "Û∞Äµ"
Manjaro = "Ôåí"
Linux = "Û∞åΩ"
Gentoo = "Û∞£®"
Fedora = "Û∞£õ"
Alpine = "ÔåÄ"
Amazon = "Ôâ∞"
Android = "Óúé"
AOSC = "ÔåÅ"
Arch = "Û∞£á"
Artix = "Û∞£á"
EndeavourOS = "ÔÜó"
CentOS = "ÔåÑ"
Debian = "Û∞£ö"
Redhat = "Û±Ñõ"
RedHatEnterprise = "Û±Ñõ"
Pop = "Ôå™"
openSUSE = "ÓΩ≠"

[username]
show_always = true
style_user = "bg:color_violet fg:color_fg0"
style_root = "bg:color_violet fg:color_fg0"
format = '[ $user ]($style)'
[username.aliases]
peterbaintner = "pb"

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 10
truncation_symbol = "‚Ä¶/"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "Û∞àô "
"Downloads" = "ÔÄô "
"Music" = "Û∞ùö "
"Pictures" = "ÔÄæ "
"Developer" = "Û∞≤ã "

[git_branch]
symbol = "Ôêò"
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[git_state]
style = "bg:color_aqua"
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[git_metrics]
disabled = false
added_style = "green bg:color_aqua"
deleted_style = "red bg:color_aqua"
format = '([+$added ]($added_style))([-$deleted ]($deleted_style))'

[nodejs]
symbol = "Óúò"
style = "bg:color_turq"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_turq)]($style)'

[c]
symbol = "Óòû "
style = "bg:color_turq"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_turq)]($style)'

[cpp]
symbol = "Óòù "
style = "bg:color_turq"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_turq)]($style)'

[rust]
symbol = "Óû®"
style = "bg:color_turq"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_turq)]($style)'

[golang]
symbol = "Óòß"
style = "bg:color_turq"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_turq)]($style)'

[php]
symbol = "Óòà"
style = "bg:color_turq"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_turq)]($style)'

[java]
symbol = "Óâñ"
style = "bg:color_turq"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_turq)]($style)'

[kotlin]
symbol = "Óò¥"
style = "bg:color_turq"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_turq)]($style)'

[haskell]
symbol = "Óòü"
style = "bg:color_turq"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_turq)]($style)'

[python]
symbol = "ÓòÜ"
style = "fg:color_fg0 bg:color_turq"
pyenv_prefix = " in "
pyenv_version_name = true
version_format = '${raw}'
format = '[${symbol}(${version})( $virtualenv) ]($style)'

[package]
style = "fg:color_fg0 bg:color_blue"
symbol = "Û∞èó "
format = '[$symbol$version ]($style)'

[docker_context]
symbol = "Ôåà"
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[pixi]
style = "bg:color_bg3"
format = '[[ $symbol( $version)( $environment) ](fg:color_fg0 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[ Ôê∫ $time ](fg:color_fg0 bg:color_bg1)]($style)'

[battery]
disabled = false
format = "[$symbol$percentage ]($style)"

[[battery.display]]
threshold = 20
style = 'bold fg:red bg:color_bg3'

[memory_usage]
disabled = false
threshold = 90
symbol = "ÓøÖ "
style = "white bold dimmed bg:color_bg3"
format = '[$symbol ${ram}( | ${swap}) ]($style)'

[line_break]
disabled = false

[fill]
symbol = '‚îÄ'
# style = 'bold green'

[character]
disabled = false
# ‚ùØ‚ùÆÔê≤ Ôê¥
success_symbol = '[‚ùØ](bold fg:color_green)'
error_symbol = '[‚ùØ](bold fg:color_red)'
vimcmd_symbol = '[‚ùÆ](bold fg:color_green)'
vimcmd_replace_one_symbol = '[‚ùÆ](bold fg:color_purple)'
vimcmd_replace_symbol = '[‚ùÆ](bold fg:color_purple)'
vimcmd_visual_symbol = '[‚ùÆ](bold fg:color_yellow)'

[cmd_duration]
style = "fg:color_fg0 bg:color_bg3"
format = "[took $duration ]($style)"

[sudo]
disabled = false
style = "bg:color_orange"
symbol = "üßô"
