# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

#î‚¶ î‚´ î‚°î‚²
format = """
[î‚¶](fg:4)\
$os\
[î‚´](bg:7 fg:4)\
$directory\
[î‚´](fg:7)\

[î‚¶](fg:5)\
$cmd_duration\
[î‚¶](fg:1 bg:5)\
$git_branch\
$git_status\
$git_state\
$git_metrics\
[î‚¶](fg:3 bg:1)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[î‚¶](fg:2 bg:3)\
$package\
[î‚¶](fg:6 bg:2)\
$docker_context\
$conda\
$pixi\
[î‚¶](fg:4 bg:6)\
$username\
$sudo\
[î‚¶](fg:7 bg:4)\
$battery\
$memory_usage\
[î‚¶](fg:0 bg:7)\
$time\
[î‚´](fg:0)\
$line_break\
$character
"""

[os]
disabled = false
format = "[$symbol ]($style)"
style = "bg:4"

[os.symbols]
Windows = "ó°²"
Ubuntu = "ó°•ˆ"
SUSE = "ïŒ”"
Raspbian = "ó°¿"
Mint = "ó°£­"
Macos = "ó°€µ"
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Gentoo = "ó°£¨"
Fedora = "ó°£›"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
AOSC = "ïŒ"
Arch = "ó°£‡"
Artix = "ó°£‡"
CachyOS = "ó°£‡"
EndeavourOS = "ï†—"
CentOS = "ïŒ„"
Debian = "ó°£š"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"
Pop = "ïŒª"
openSUSE = "î½­"

[username]
show_always = true
style_user = "bg:4 "
style_root = "bg:4 "
format = '[ $user ]($style)'
[username.aliases]
peterbaintner = "pb"

[directory]
style = "bg:7"
format = "[ $path ]($style)"
truncation_length = 10
truncation_symbol = "â€¦/"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ó°š "
"Pictures" = "ï€¾ "
"Developer" = "ó°²‹ "

[git_branch]
symbol = "ï˜"
style = "bg:1"
format = '[[ $symbol $branch ]( bg:1)]($style)'

[git_status]
style = "bg:1"
format = '[[($all_status$ahead_behind )]( bg:1)]($style)'

[git_state]
style = "bg:1"
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[git_metrics]
disabled = false
added_style = "fg:#005d30 bg:1"
deleted_style = "fg:#5d0030 bg:1"
format = '([+$added ]($added_style))([-$deleted ]($deleted_style))'

[nodejs]
symbol = "îœ˜"
style = "bg:3"
format = '[[ $symbol( $version) ]( bg:3)]($style)'

[c]
symbol = "î˜ "
style = "bg:3"
format = '[[ $symbol( $version) ]( bg:3)]($style)'

[cpp]
symbol = "î˜ "
style = "bg:3"
format = '[[ $symbol( $version) ]( bg:3)]($style)'

[rust]
symbol = "î¨"
style = "bg:3"
format = '[[ $symbol( $version) ]( bg:3)]($style)'

[golang]
symbol = "î˜§"
style = "bg:3"
format = '[[ $symbol( $version) ]( bg:3)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:3"
format = '[[ $symbol( $version) ]( bg:3)]($style)'

[java]
symbol = "î‰–"
style = "bg:3"
format = '[[ $symbol( $version) ]( bg:3)]($style)'

[kotlin]
symbol = "î˜´"
style = "bg:3"
format = '[[ $symbol( $version) ]( bg:3)]($style)'

[haskell]
symbol = "î˜Ÿ"
style = "bg:3"
format = '[[ $symbol( $version) ]( bg:3)]($style)'

[python]
symbol = "î˜†"
style = " bg:3"
pyenv_prefix = " in "
pyenv_version_name = true
version_format = '${raw}'
format = '[${symbol}(${version})( $virtualenv) ]($style)'

[package]
style = " bg:2"
symbol = "ó°— "
format = '[$symbol$version ]($style)'

[docker_context]
symbol = "ïŒˆ"
style = "bg:7"
format = '[[ $symbol( $context) ](fg:#83a598 bg:7)]($style)'

[conda]
style = "bg:7"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:7)]($style)'

[pixi]
style = "bg:7"
format = '[[ $symbol( $version)( $environment) ]( bg:7)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:0"
format = '[[ ïº $time ]( bg:0)]($style)'

[battery]
disabled = false
format = "[$symbol$percentage ]($style)"

[[battery.display]]
threshold = 20
style = 'bold fg:red bg:7'

[memory_usage]
disabled = false
threshold = 90
symbol = "î¿… "
style = "bg:7"
format = '[$symbol ${ram}( | ${swap}) ]($style)'

[line_break]
disabled = false

[fill]
symbol = 'â”€'
style = 'selection-background'

[character]
disabled = false
# â¯â®ï² ï´
success_symbol = '[â¯](bold)'
error_symbol = '[â¯](bold fg:1)'
vimcmd_symbol = '[â®](bold )'
vimcmd_replace_one_symbol = '[â®](bold fg:5)'
vimcmd_replace_symbol = '[â®](bold fg:5)'
vimcmd_visual_symbol = '[â®](bold fg:3)'

[cmd_duration]
style = " bg:5"
format = "[took $duration ]($style)"

[sudo]
disabled = false
style = " bg:4"
symbol = "ğŸ§™"
format = "[as $symbol]($style)"
